In [1]:
import numpy as np

arr = np.array([5,8,10,12,16,20])
print(arr)
print(type(arr))

[ 5  8 10 12 16 20]
<class 'numpy.ndarray'>


In [6]:
# Addition
import numpy as np

arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([1, 2, 3, 4, 5])

new_arr = arr_1 + arr_2

print(f"Output is : {new_arr}")

Output is : [ 2  4  6  8 10]


In [ ]:
# Subtract
import numpy as np

arr_1 = np.array([2, 4, 6, 8, 10])
arr_2 = np.array([1, 2, 3, 4, 5])

new_arr = arr_1 - arr_2

print(f"Output is : {new_arr}")

Output is : [1 2 3 4 5]


In [ ]:
# Multiply
import numpy as np

arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([1, 2, 3, 4, 5])

new_arr = arr_1 * arr_2

print(f"Output is : {new_arr}")

Output is : [ 1  4  9 16 25]


In [12]:
# Divide
import numpy as np

arr_1 = np.array([10, 20, 30, 40, 50])
arr_2 = np.array([1, 2, 3, 4, 5])

new_arr = arr_1 / arr_2

print(f"Output is : {new_arr}")

Output is : [10. 10. 10. 10. 10.]


In [19]:
# Squaring inbuilt function
import numpy as np

arr_1 = np.array([16, 9, 100])

new_arr = np.square(arr_1)

print(f"Output is : {new_arr}")

Output is : [  256    81 10000]


In [ ]:
# Mean inbuilt function
import numpy as np

arr_1 = np.array([16, 9, 100])

new_arr = np.mean(arr_1)

print(f"Output is : {new_arr}")

Output is : 41.666666666666664


In [ ]:
# Sum inbuilt function
import numpy as np

arr_1 = np.array([16, 9, 100])

new_arr = np.sum(arr_1)
print(f"Output is : {new_arr}")

Output is : 125


In [20]:
# Max inbuilt function
import numpy as np

arr_1 = np.array([16, 9, 100])

new_arr = np.max(arr_1)

print(f"Output is : {new_arr}")

Output is : 100


In [21]:
# Min inbuilt function
import numpy as np

arr_1 = np.array([16, 9, 100])

new_arr = np.min(arr_1)

print(f"Output is : {new_arr}")

Output is : 9


In [ ]:
# Multi Dimensional Array

import numpy as np

arr_2d = np.array([[10, 11, 12, 13] , [1, 2, 3, 4]])

print(f"Output is : {arr_2d}")

Output is : [[10 11 12 13]
 [ 1  2  3  4]]
Output is : 8
Output is : 0


In [28]:
import numpy as np

arr_2d = np.array([[10, 11, 12, 13] , [1, 2, 3, 4]])

print(f"Output is : {arr_2d}")
print(f"Output is : {arr_2d.size}")

Output is : [[10 11 12 13]
 [ 1  2  3  4]]
Output is : 8


In [29]:
import numpy as np

arr_2d = np.array([[10, 11, 12, 13] , [1, 2, 3, 4]])

print(f"Output is : {arr_2d}")
print(f"Output is : {arr_2d.ndim}")

Output is : [[10 11 12 13]
 [ 1  2  3  4]]
Output is : 2


In [30]:
import numpy as np

arr_2d = np.array([[10, 11, 12, 13] , [1, 2, 3, 4]])

print(f"Output is : {arr_2d}")
print(f"Output is : {arr_2d.shape}")

Output is : [[10 11 12 13]
 [ 1  2  3  4]]
Output is : (2, 4)


In [35]:
import numpy as np

arr_1 = np.array([[[8, 3, 1],[5, 9, 8]] , [[20, 10, 11],[6, 4, 3]]])

print(f"Output is : {arr_1}")
print(f"Size is : {arr_1.size}")
print(f"Ndim is : {arr_1.ndim}")
print(f"Shape is : {arr_1.shape}")


Output is : [[[ 8  3  1]
  [ 5  9  8]]

 [[20 10 11]
  [ 6  4  3]]]
Size is : 12
Ndim is : 3
Shape is : (2, 2, 3)


In [36]:
import numpy as np

arr_1 = np.array([[[[8, 3, 1],[5, 9, 8],[1, 2, 3]]] , [[[20, 10, 11],[6, 4, 3],[1,2,3]]]])

print(f"Output is : {arr_1}")
print(f"Size is : {arr_1.size}")
print(f"Ndim is : {arr_1.ndim}")
print(f"Shape is : {arr_1.shape}")

Output is : [[[[ 8  3  1]
   [ 5  9  8]
   [ 1  2  3]]]


 [[[20 10 11]
   [ 6  4  3]
   [ 1  2  3]]]]
Size is : 18
Ndim is : 4
Shape is : (2, 1, 3, 3)


In [44]:
# dtype

import numpy as np

arr_1 = np.array([5, 9, 10, 15])

print(arr_1.dtype)

int64


In [45]:
# Array Indexing

# 1D

import numpy as np

arr_1 = np.array([1, 2, 3, 4])

print(arr_1[2])

3


In [46]:
# 2D

import numpy as np

arr_1 = np.array([[1, 2, 3, 4] , [2, 4, 6, 8]])
print(arr_1[1,2])

6


In [ ]:
# Negative Indexing

import numpy as np

arr_1 = np.array([[1, 2, 3, 4] , [2, 4, 6, 8]])
print(arr_1[ -2, -2])

3


In [ ]:
# Boolean Indexing

import numpy as np

arr = np.array([30, 10, 40, 50, 20])
condition = arr > 25

print(arr[condition])

# print(arr[arr > 25]) Indrustry Level

[30 40 50]
[30 40 50]


In [67]:
#Excersice

import numpy as np

arr = np.array([30, 10, 40, 50, 20])

print(f"Output is : {arr[(arr > 25) & (arr < 45)]}")

Output is : [30 40]


In [ ]:
#Excersice

import numpy as np

patient_temp = np.array([
    [31, 30, 28], 
    [29, 29, 32], 
    [26, 24, 27], 
    [31, 34, 35], 
    [28, 31, 30]
])

avarage_temp = np.mean(patient_temp)

print(f"Avarage temp is : {avarage_temp}")

print(patient_temp [patient_temp > avarage_temp])

Avarage temp is : 29.666666666666668
[31 30 32 31 34 35 31 30]


In [ ]:
# Value Initialize Using zeros
# 1D
import numpy as np

print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
# Value Initialize Using zeros
# 2D
import numpy as np

print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Value Initialize Using ones
# 1D
import numpy as np

print(np.ones(5))

[1. 1. 1. 1. 1.]


In [ ]:
# Value Initialize Using ones
# 2D
import numpy as np

print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [78]:
# Value Initialize Using ones.We can assign any value
# 2D
import numpy as np

print(np.full((2,3), 7))

[[7 7 7]
 [7 7 7]]


In [85]:
import numpy as np

print(np.full((2,3), [1,2,3]))

[[1 2 3]
 [1 2 3]]


In [88]:
print(np.empty((2,3)))

[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]]
